### ISSUE TITLE
Could not load JSONAPI

### ISSUE THREAD

**Issue by mafen** [Bukkit-Forge-Plugins/Bukkit-Forge-Plugin-Errors#11]
2013-01-14 22:32:13 [SEVERE] [BukkitForge] Could not load './plugins/JSONAPI.jar' in folder './plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:184)
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:305)
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:230)
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.loadPlugins(BukkitServer.java:908)
at keepcalm.mods.bukkit.bukkitAPI.BukkitServer.(BukkitServer.java:269)
at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:47)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Unknown Source)
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:173)
... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_6.World
at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:70)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 9 more
2013-01-14 22:32

http://forums.bukkit.org/threads/admn-info-jsonapi-v4-1-0-json-http-and-socket-api-for-controlling-a-server-1-4-6.14270/¨

BukkitForge-1.4.7-88.jar

**Comment by alecgorge** [comment]
This is fixed in JSONAPI v4.3.0
